[System]
Language = 1                    # English = 1; Japanese = 2; German = 3; French = 4; Spanish = 5; Italian = 6.
Hints = true
ScoreBehaviour = 0              # Reset to zero = 0; Reset to last checkpoint score = 1.
UnleashOutOfControlDrain = true
WerehogHubTransformVideo = true
LogoSkip = false

[Controls]
CameraXInvert = false
CameraYInvert = false
XButtonHoming = true
UnleashCancel = false

[Audio]
MusicVolume = 1.0
SEVolume = 1.0
VoiceLanguage = 0               # English = 0; Japanese = 1.
Subtitles = true
WerehogBattleMusic = true

[Video]
GraphicsAPI = 0                 # D3D12 = 0; Vulkan = 1.
WindowWidth = 1280
WindowHeight = 720
ResolutionScale = 1.0
Fullscreen = false
VSync = true
BufferCount = 3                 # Double buffering = 2; Triple buffering = 3.
FPS = 60                        # Unlocked = -1; 30 FPS = 30; 60 FPS = 60.
Brightness = 0.5
MSAA = 4
AnisotropicFiltering = 16
ShadowResolution = 4096         # Default = -1; otherwise, any power of two resolution.
GITextureFiltering = 1          # Linear = 0; Bicubic = 1.
AlphaToCoverage = true
Xbox360ColorCorrection = false
MovieScaleMode = 1              # Stretch = 0; Fit = 1; Fill = 2.
UIScaleMode = 2                 # Stretch = 0; Edge = 1; Centre = 2.